In [ ]:
# What I learned

Numpy

NumPy (short for Numerical Python) is a Python library used to work with 

* numbers 
* arrays 
* math operations 

easily and fast.

NumPy = fast math with lots of numbers in Python

NumPy = “Do the same math to many numbers at once

Side-by-Side Comparison Python list vs Numpy Array

Thing	                  Python List 🧸	                              NumPy Array 🧱
Looks like	              Loose/scattered on the floor LEGO pieces	      Connected LEGO
Math	                  One by one	                                  All at once
Speed	                  Slower	                                      Very fast 🚀
Used for	              General coding	                              Math, data, AI





In [1]:
import numpy as np

In [2]:
my_list = [1,2,3,4,5]

In [3]:
first_array = np.array(my_list)

In [4]:
first_array

array([1, 2, 3, 4, 5])

In [5]:
np.shape(first_array)

(5,)

In [6]:
second_array = [6,7,8,9,10]
third_array = [11,12,13,14,15]

In [8]:
multidim_array = np.array([first_array, second_array, third_array])

In [9]:
multidim_array


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [11]:
type(multidim_array)

numpy.ndarray

In [12]:
multidim_array.shape

(3, 5)

In [13]:
multidim_array.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [ ]:
# Indexing -> start from 0

Array indexing = pointing to a LEGO block by its seat number (always starting from 0)

What is array indexing?

Array indexing means accessing a value from an array using its position number.

1. In Python (and NumPy), indexing starts from 0.

2. Negative indexing (from the end)

   You can count from the end using negative numbers.

3. Indexing in a 2D array (rows & columns). 

4. Use [] to access elements.




In [14]:
multidim_array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [15]:
multidim_array[0][0]

np.int64(1)

In [22]:
print(multidim_array[1,2])

8


In [19]:
print(multidim_array[:][2])

[11 12 13 14 15]


In [20]:
print(multidim_array[:])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [21]:
print(multidim_array[:][:])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [29]:
print(multidim_array[1:,3:])

[[ 9 10]
 [14 15]]


In [30]:
print(multidim_array[1:,2:4])

[[ 8  9]
 [13 14]]


In [31]:
print(multidim_array[1:2,1:4])

[[7 8 9]]


In [32]:
multidim_array[1:2,1:4]

array([[7, 8, 9]])

In [33]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
arr

array([  1,   6,  11, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100])

In [40]:
# copy function and broadcasting

arr[3:]=100

In [41]:
arr

array([  1,   6,  11, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100])

In [43]:
# arrays are reference type

array_1 = np.arange(0,10)
array_1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
#array_1[3:] = 100
array_2 = array_1
array_2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
array_2[3:] = 100

In [47]:
array_2

array([  0,   1,   2, 100, 100, 100, 100, 100, 100, 100])

In [48]:
array_1

array([  0,   1,   2, 100, 100, 100, 100, 100, 100, 100])

In [51]:
array_3 = array_1.copy()
array_3

array([  0,   1,   2, 100, 100, 100, 100, 100, 100, 100])

In [53]:
array_3[3:] = 1000
array_3


array([   0,    1,    2, 1000, 1000, 1000, 1000, 1000, 1000, 1000])

In [54]:
array_1

array([  0,   1,   2, 100, 100, 100, 100, 100, 100, 100])

In [34]:
arr = np.arange(0,10,step = 2)


In [35]:
arr

array([0, 2, 4, 6, 8])

In [36]:
arr = np.arange(1,100,step = 5)

In [37]:
arr

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [38]:
np.linspace(1,2,50)

array([1.        , 1.02040816, 1.04081633, 1.06122449, 1.08163265,
       1.10204082, 1.12244898, 1.14285714, 1.16326531, 1.18367347,
       1.20408163, 1.2244898 , 1.24489796, 1.26530612, 1.28571429,
       1.30612245, 1.32653061, 1.34693878, 1.36734694, 1.3877551 ,
       1.40816327, 1.42857143, 1.44897959, 1.46938776, 1.48979592,
       1.51020408, 1.53061224, 1.55102041, 1.57142857, 1.59183673,
       1.6122449 , 1.63265306, 1.65306122, 1.67346939, 1.69387755,
       1.71428571, 1.73469388, 1.75510204, 1.7755102 , 1.79591837,
       1.81632653, 1.83673469, 1.85714286, 1.87755102, 1.89795918,
       1.91836735, 1.93877551, 1.95918367, 1.97959184, 2.        ])

In [39]:
np.linspace(1,2,5)

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [56]:
# random distribution 
arr_exp = np.random.rand(3,3)

In [57]:
arr_exp 

array([[0.9584745 , 0.72330227, 0.72480689],
       [0.54945532, 0.81722438, 0.35492132],
       [0.03022844, 0.98063426, 0.38397697]])

In [58]:
arr_exp = np.random.rand(3,3)
arr_exp

array([[0.77368498, 0.33182941, 0.33300343],
       [0.2830982 , 0.12380428, 0.72686542],
       [0.69776877, 0.98120274, 0.779569  ]])

In [62]:
np.random.randint(0,100,8)

array([67, 36,  9, 72,  4, 43,  0, 31])

In [64]:
np.random.randint(0,100,8).reshape(2,2)

ValueError: cannot reshape array of size 8 into shape (2,2)